---
title: "Food Price Index and Search Word from Anna's session"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(gtrendsR)
library(lubridate)
library(here)
library(zip)
```

# Data Source
Food Price Index Selected Monthly Weighted Average Prices for New Zealand (Monthly): http://infoshare.stats.govt.nz/infoshare/SelectVariables.aspx?pxID=9a605fc4-8202-45d6-9736-9d97ddffccdc
Search Data: Google Trend


# Load Data
```{r}

temp <- tempfile()
download.file("https://www.stats.govt.nz/assets/Uploads/Food-price-index/Food-price-index-October-2020/Download-data/food-price-index-october-2020-csv-tables.zip",temp)
food <- read_csv(unz(temp, zip_list(temp)$filename[stringr::str_detect(zip_list(temp)$filename,"average")])) %>% 
  select(Period, Data_value, Series_title_1) %>% 
  mutate(Period = as.character(Period)) %>% 
  separate(., Period, c("Year", "Months"), sep = "\\.") %>%
  mutate(Months = if_else(Months == "1", "10", Months)) %>% 
  mutate(Time = paste(Year, Months, "01", sep = "-")) %>%
  mutate(Time = as.Date(Time, format = "%Y-%m-%d"),
         Food = substr(Series_title_1, 1, str_locate(Series_title_1, ",")[,1]-1))
unlink(temp)

foodName <- unique(food$Food)[stringr::str_detect(unique(food$Food), "Avocado")]

search <- gtrends(keyword = foodName, geo = "NZ")$interest_over_time %>% 
  group_by(Time = floor_date(date, "month")) %>%
  summarize(averageHitsPerMonth = mean(hits))

data <- left_join(search,
                  food,
                  by = c("Time" = "Time"))


```

# Plot
```{r}
title_word <- food %>% filter(Food == foodName) %>% select(Series_title_1) %>% unique()
food %>% filter(Food == foodName) %>% 
  ggplot(., aes(x = Time, y = Data_value)) +
  geom_line(size = 2) +
  labs(title = title_word,
       y = "Price (NZ$)")

data %>% filter(Food == foodName) %>% 
  ggplot(., aes(x = averageHitsPerMonth, y = Data_value)) +
  geom_point() +
  labs(title = foodName,
       caption = "Source: NZ Stats",
       y = "Price (NZ$)",
       x = "Average Search per Month")

```

```{r}

```



# Reference
Food price index resource: http://infoshare.stats.govt.nz/survey-participants/survey-resources/fpi-resource.aspx#gsc.tab=0
CSV File: https://www.stats.govt.nz/large-datasets/csv-files-for-download/
Oc 2020: https://www.stats.govt.nz/assets/Uploads/Food-price-index/Food-price-index-October-2020/Download-data/food-price-index-october-2020-csv-tables.zip
